setup:
    prefix: 'j2s7s300_driver'
    model_filename: "jaco_dynamics"
    object_centers: {'HUMAN_CENTER': [-0.6,-0.55,0.0], 'LAPTOP_CENTER': [-0.7929,-0.1,0.0]}
    start: [104.2, 151.6, 183.8, 101.8, 224.2, 216.9, 310.8]
    T: 20.0
    timestep: 0.5
    feat_list: ["table", "laptop"]
    # demo_spec: "all_0" # "simulate", "all" followed by task number, ID number followed by task number
    demo_spec: "simulate"
    demo_dir: "/data/demonstrations/demos/"
